spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: username
    password: password

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名和下划线命名的自动转换

tencent:
  cos:
    secret-id: secret_id
    secret-key: secret_key